---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: economic efficiency faq, bluexp, lifecycle planning frequently asked questions 
summary: 'El servicio de planificación del ciclo de vida de NetApp identifica clústeres con capacidad baja actual o prevista y le brinda recomendaciones sobre niveles de datos o capacidad adicional (para sistemas AFF ).  El servicio también proporciona recomendaciones de actualización tecnológica en sistemas que están llegando al final de su vida útil.' 
---
= Novedades en la planificación del ciclo de vida
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Descubra las novedades en la planificación del ciclo de vida.



== 6 de octubre de 2025



=== La BlueXP economic efficiency ahora es la planificación del ciclo de vida

La BlueXP economic efficiency ha pasado a llamarse Planificación del ciclo de vida.

Puede acceder a él desde la barra de navegación izquierda de la NetApp Console seleccionando *Almacenamiento* > *Planificación del ciclo de vida*.



=== BlueXP ahora es NetApp Console

La NetApp Console, construida sobre la base BlueXP mejorada y reestructurada, proporciona una gestión centralizada del almacenamiento de NetApp y de los NetApp Data Services en entornos locales y en la nube a nivel empresarial, brindando información en tiempo real, flujos de trabajo más rápidos y una administración simplificada, que es altamente segura y compatible.

Para obtener más detalles sobre lo que ha cambiado, consulte lalink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de la versión de la NetApp Console"] .



== 15 de mayo de 2024



=== Funciones deshabilitadas

Algunas funciones de BlueXP economic efficiency se han desactivado temporalmente:

* Actualización tecnológica
* Añadir capacidad




== 14 de marzo de 2024



=== Opciones de actualización tecnológica

Si tiene activos existentes y desea determinar si es necesario actualizar una tecnología, puede utilizar las opciones de actualización de tecnología de eficiencia económica de BlueXP .  Puede revisar una evaluación breve de sus cargas de trabajo actuales y obtener recomendaciones o, si envió registros de AutoSupport a NetApp en los últimos 90 días, el servicio ahora puede proporcionar una simulación de carga de trabajo para ver cómo funcionan sus cargas de trabajo en hardware nuevo.

También puede agregar una carga de trabajo y excluir cargas de trabajo existentes de la simulación.

Anteriormente, solo era posible realizar una evaluación de sus activos e identificar si era recomendable actualizar su tecnología.

La función ahora es parte de la opción Actualización de tecnología en la navegación izquierda.

Obtenga más información sobre el https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["Evaluar una actualización tecnológica"] .



== 08 de noviembre de 2023



=== Actualización tecnológica

Esta versión de BlueXP economic efficiency incluye una nueva opción para realizar una evaluación de sus activos e identificar si se recomienda una actualización tecnológica.  La BlueXP economic efficiency incluye una nueva opción de actualización tecnológica en la navegación izquierda, nuevas páginas en las que puede realizar una evaluación de sus cargas de trabajo y activos actuales y un informe que le brinda recomendaciones.



== 02 de abril de 2023



=== Presentamos la BlueXP economic efficiency

La nueva BlueXP economic efficiency identifica activos de almacenamiento con baja capacidad actual o prevista y brinda recomendaciones sobre niveles de datos o capacidad adicional para sistemas AFF locales.

link:https://docs.netapp.com/us-en/bluexp-economic-efficiency/get-started/intro.html["Obtenga más información sobre la eficiencia económica de NetApp"] .
